sudo: false
dist: trusty
language: java
jdk:
    - oraclejdk8
    - oraclejdk9
    - oraclejdk10
    - openjdk8
    - openjdk9
    - openjdk10
install: skip
script:
    - java -version
    - which java
    - echo $JAVA_HOME
    - 'tr : "\n" <<<$PATH'
notifications:
  email: never
