os:
- osx
language: scala
sudo: true
dist: trusty
addons:
  apt:
    update: true
    packages:
    - numactl
    - libnuma1
    - libnuma-dev
    - libnuma-dbg
scala: 
- 2.12.6
jdk:
- oraclejdk8
env:
  - CI_CATEGORY=UNIT_TESTS
before_install:
  - ./.ci_scripts/beforeInstall.sh $CI_CATEGORY $MONGO_VER $MONGO_PROFILE /tmp/integration-env.sh
  - if [ "x$CI_CATEGORY" = "xINTEGRATION_TESTS" ]; then (./.ci_scripts/fork-mongod.sh /tmp/integration-env.sh); fi
script:
  - export SCALA_VERSION="$TRAVIS_SCALA_VERSION"
  - ./.ci_scripts/retry.sh 3 ./.ci_scripts/validate.sh /tmp/integration-env.sh
