sudo: required
language: java
addons:
    apt:
        - atool
        - vim
jobs:
    include:
        - env: run=trusty-stable
          dist: trusty
        - env: run=trusty-old
          dist: trusty
          group: deprecated-2017Q2
        - env: run=precise
          dist: precise
        - env: run=xenial
          dist: xenial
install: skip
script: skip
notifications:
  email: never

