sudo: required
dist: xenial
#group: edge
install: skip
language: python
services:
- postgresql
script:
- psql -c 'select * from version()'
- |
    psql -c "select setting from pg_settings where name = 'data_directory';" | awk 'BEGIN{e=1};1;/ramfs/{e=0};END{exit e}'
notifications:
  email: never

