sudo: required
language: java
jobs:
    include:
        - env: test='openjdk not on image'
          jdk: openjdk9
          dist: precise
        - env: test='openjdk on image'
          jdk: openjdk7
          dist: precise
        - env: test='oraclejdk not on image'
          jdk: oraclejdk11
          dist: precise
        - env: test='oraclejdk on image'
          jdk: oraclejdk9
          dist: precise
install: "ls -la /usr/lib/jvm /usr/local/lib/jvm || true"
script:
    - which java
    - ls -l `which java`
    - "tr : '\n' <<<$PATH"
    - echo $JAVA_HOME
notifications:
  email: never

