sudo: false
dist: trusty
language: java
jdk:
    - openjdk9
    - openjdk10

    - oraclejdk9
    - oraclejdk10
install: "ls -la /usr/lib/jvm /usr/local/lib/jvm || true"
script:
    - which java
    - ls -l `which java`
    - "tr : '\n' <<<$PATH"
    - echo $JAVA_HOME
notifications:
  email: never

