sudo: false
dist: trusty
language: java
jdk:
    - openjdk7
    - openjdk8
    - openjdk9
    - openjdk10

    - oraclejdk7
    - oraclejdk8
    - oraclejdk9
    - oraclejdk10
install: skip
script:
    - which java
    - ls -l `which java`
    - "tr : '\n' <<<$PATH"
    - echo $JAVA_HOME
notifications:
  email: never

